image: quay.io/dennybaa/droneruby
env:
  - DEBUG=1
  - ST2_GITURL=https://github.com/StackStorm/st2
  - ST2_GITREV=master
  - ST2_WAITFORSTART=20
  - ST2_TESTMODE=
  - ST2_BUILDLIST=
  - BUILDHOST=packagingenv
  - TESTHOSTS=droneunit
script:
  - ./.drone/build.sh
services:
  - quay.io/dennybaa/droneunit:trusty-upstart
  - quay.io/stackstorm/packagingenv:trusty
  - rabbitmq
  - mongodb
