image: quay.io/stackstorm/packagingrunner
env:
  - DEBUG_LEVEL=debug
  - BUILDNODE=packagingenv
  - TESTNODE=droneunit
  - ST2_GITURL=https://github.com/stackstorm/st2
  - ST2_GITREV=master
  - ST2_PYTHON=0
  - POSTGRES_USER=mistral
  - POSTGRES_PASSWORD=StackStorm
script: 
   - cp /root/Gemfile ./
   - "bundle exec rake && bundle exec rspec"

services:
  - quay.io/dennybaa/droneunit:wheezy-sshd
  - quay.io/stackstorm/packagingenv:wheezy
  - rabbitmq
  - mongodb
  - library/postgres
