image: quay.io/dennybaa/droneruby-ubuntu
env:
  # List of available st2 packages (must have correct installation order)
  - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor
  - ST2_GITURL=https://github.com/dennybaa/st2.git
  - ST2_GITREV=setuptools_packaging_improvements
  - BUILDHOST=st2packages-buildenv-deb
  - TESTHOST=droneunit-ubuntu-upstart
  - DEBUG=1
script:
  - ./.drone/build.sh
services:
  - quay.io/dennybaa/droneunit-ubuntu-upstart
  - quay.io/stackstorm/st2packages-buildenv-deb
