image: quay.io/dennybaa/droneruby-ubuntu
env:
  # Full list of st2 packages configures the default build
  - ST2_PACKAGES="st2common st2actions st2api st2auth st2client st2reactor"
  - ST2_GITURL=https://github.com/dennybaa/st2.git
  - ST2_GITREV=setuptools_packaging_improvements
script:
  - ./.drone/build.sh
services:
  - quay.io/stackstorm/st2packages-buildenv-deb
