image: quay.io/stackstorm/packagingrunner
env:
  - DEBUG_LEVEL=debug
  - ST2_GITURL=https://github.com/stackstorm/st2
  - ST2_GITREV=master
  - ST2_PYTHON=0
  # - ST2_WAITFORSTART=20
  # - ST2_TESTMODE=
  # - ST2_BUILDLIST=st2auth
  # - MISTRAL_ENABLED=0
  # - MISTRAL_GITURL=https://github.com/StackStorm/mistral
  # - MISTRAL_GITREV=st2-0.13.2
  # - MISTRAL_VERSION=2015.2
  # - MISTRAL_RELEASE=1
  # - POSTGRES_USER=mistral
  # - POSTGRES_PASSWORD=StackStorm
  - BUILDNODE=packagingenv
  # - TESTHOSTS=droneunit
script:
  - bash -c "cp /root/Gemfile ./; bundle exec rake"
services:
  - quay.io/dennybaa/droneunit:wheezy-sshd
  - quay.io/stackstorm/packagingenv:wheezy
  # - rabbitmq
  # - mongodb
  # - library/postgres
