image: quay.io/dennybaa/droneunit-ubuntu:latest
env:
  - BUILDHOST=st2packages-buildenv-deb
script:
  - alias ssh='ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
  - cat /etc/hosts
  - pwd
  - find ./
  - ssh busybee@$BUILDHOST cat /etc/hosts || true
services:
  - quay.io/stackstorm/st2packages-buildenv-deb:latest
