image: quay.io/dennybaa/droneruby
env:
  # List of available st2 packages (must have correct installation order)
  - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor st2debug st2exports
  - ST2_GITURL=https://github.com/dennybaa/st2
  - ST2_GITREV=updates_for_st2_packaging
  - ST2_WAITFORSTART=20
  - DEBUG=1
  # If BUILDLIST differs form ST2_PACKAGES, no spec tests are run.
  # Spec tests require all packages to be available. Tests also can be disabled
  # by emptying TESTHOSTS.
  - BUILDLIST=
  - BUILDHOST=packagingenv
  - TESTHOSTS=droneunit
script:
  - ./.drone/build.sh
services:
  - quay.io/dennybaa/droneunit:trusty-upstart
  - quay.io/stackstorm/packagingenv:trusty
  - rabbitmq
  - mongodb
