image: quay.io/dennybaa/droneruby
env:
  # List of available st2 packages (must have correct installation order)
  - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor
  - ST2_GITURL=https://github.com/dennybaa/st2.git
  - ST2_GITREV=setuptools_packaging_improvements
  - ST2_WAITFORSTART=20
  # If given and differs form ST2_PACKAGES, no spec tests are run.
  # Spec tests require all packages to be available.
  - BUILDLIST=st2common st2client
  - BUILDHOST=packagingenv
  # - TESTHOSTS=droneunit
  - DEBUG=1
script:
  - ./.drone/build.sh
services:
  # - quay.io/dennybaa/droneunit:trusty-upstart
  - quay.io/stackstorm/packagingenv:rpm
  - rabbitmq
  - mongodb
