## Suites configuration
#
suite:
  image: fake
  working_dir: /root/st2-packages
  command: >-
    bash -c "cp /root/Gemfile* ./ &&
              bundle exec rake &&
              bundle exec rspec"
  environment:
    - DEBUG_LEVEL=0
    - ST2_GITURL=https://github.com/dennybaa/st2
  volumes:
    - .:/root/st2-packages
    - /tmp/st2-packages:/root/build

suite-compose:
  image: fake
  extends:
    file: compose.yml
    service: suite

suite-circle:
  image: fake
  command: >-
    bash -c "cp /root/Gemfile* ./ &&
              bundle exec rake"
  extends:
    file: compose.yml
    service: suite
  environment:
    - RABBITMQHOST=172.17.42.1
    - POSTGRESHOST=172.17.42.1
    - MONGODBHOST=172.17.42.1
  volumes:
    - /home/ubuntu/.cache/pip:/root/.cache/pip

# Host built artifacts directory should
# match $ARTIFACT_DIR for ease of use in compose
artifacts_volume:
  image: fake
  volumes:
    - /tmp/st2-packages:/root/build


## Service used by st2
#
rabbitmq:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "15672:15672"  # managment plugin port
    - "5672:5672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"

postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=mistral
    - POSTGRES_PASSWORD=StackStorm

## Package build nodes
#
wheezybuild:
  image: quay.io/stackstorm/packagingenv:wheezy
  extends:
    file: compose.yml
    service: artifacts_volume

jessiebuild:
  image: quay.io/stackstorm/packagingenv:jessie
  extends:
    file: compose.yml
    service: artifacts_volume

trustybuild:
  image: quay.io/stackstorm/packagingenv:trusty
  extends:
    file: compose.yml
    service: artifacts_volume

centos6build:
  image: quay.io/stackstorm/packagingenv:centos6
  extends:
    file: compose.yml
    service: artifacts_volume

centos7build:
  image: quay.io/stackstorm/packagingenv:centos7
  extends:
    file: compose.yml
    service: artifacts_volume


## Package testing nodes
#
wheezytest:
  image: quay.io/dennybaa/droneunit:wheezy-sshd
  extends:
    file: compose.yml
    service: artifacts_volume

jessietest:
  image: quay.io/dennybaa/droneunit:jessie-sshd
  extends:
    file: compose.yml
    service: artifacts_volume

trustytest:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  extends:
    file: compose.yml
    service: artifacts_volume

centos6test:
  image: quay.io/dennybaa/droneunit:centos6-sshd
  extends:
    file: compose.yml
    service: artifacts_volume

centos7test:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  extends:
    file: compose.yml
    service: artifacts_volume
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
