
suite:
  working_dir: /root/st2-packages
  command: bash -c "cp /root/Gemfile ./; bundle exec rake"
  environment:
    - DEBUG_LEVEL=0
    - COMPOSE=1
    - ST2_PYTHON=
  volumes:
    - .:/root/st2-packages
    - /tmp/st2-build:/root/st2-build
