# docker-compose >= 1.3.0rc3

buildenvdeb: 
  image: quay.io/stackstorm/buildenv-pkg:deb
  volumes:
    - /tmp/st2-packages:/root/build

specubuntu:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  volumes_from:
    - buildenvdeb

ubuntu:
  image: quay.io/dennybaa/droneruby
  working_dir: /root/workdir
  entrypoint: ["/bin/bash", "/root/workdir/.drone/build.sh"]
  environment:
    # Full list of st2 packages configures the default build
    - COMPOSE=1
    - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor
    - ST2_GITURL=https://github.com/dennybaa/st2.git
    - ST2_GITREV=setuptools_packaging_improvements
    - BUILDHOST=buildenvdeb
    - TESTHOST=specubuntu
    - DEBUG=1
  links:
    - buildenvdeb
    - specubuntu
  volumes:
    - .:/root/workdir
    - /tmp/st2-packages:/root/packages
