# docker-compose >= 1.3.0rc3

buildenvdeb: 
  image: quay.io/stackstorm/st2packages-buildenv-deb

ubuntu:
  build: .
  dockerfile: package/Dockerfile.ubuntu
  environment:
    - BUILDHOST=buildenvdeb
    - ST2_GITURL=https://github.com/dennybaa/st2.git
    - ST2_GITREV=setuptools_packaging_improvements
  links:
    - buildenvdeb
