wheezy:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=wheezybuild
  links:
    - wheezybuild

trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=trustybuild
  links:
    - trustybuild

centos7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=centos7build
  links:
    - centos7build

centos6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
  links:
    - centos6build

rabbitmq:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "15672:15672"  # managment plugin port
    - "5672:5672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"

postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=mistral
    - POSTGRES_PASSWORD=StackStorm

# Package build nodes
wheezybuild:
  image: quay.io/stackstorm/packagingenv:wheezy
  volumes:
    - /tmp/st2-packages:/root/build

trustybuild:
  image: quay.io/stackstorm/packagingenv:trusty
  volumes:
    - /tmp/st2-packages:/root/build

centos6build:
  image: quay.io/stackstorm/packagingenv:centos6
  volumes:
    - /tmp/st2-packages:/root/build

centos7build:
  image: quay.io/stackstorm/packagingenv:centos7
  volumes:
    - /tmp/st2-packages:/root/build


# Package testing nodes
wheezytest:
  image: quay.io/dennybaa/droneunit:wheezy-sshd
  volumes:
    - /tmp/st2-packages:/root/build

trustytest:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  volumes:
    - /tmp/st2-packages:/root/build

centos6test:
  image: quay.io/dennybaa/droneunit:centos6-sshd
  volumes:
    - /tmp/st2-packages:/root/build

centos7test:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /tmp/st2-packages:/root/build
