# docker-compose >= 1.3.0rc3

rabbitmq:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "15672:15672"  # managment plugin port
    - "5672:5672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"

buildenvdeb: 
  image: quay.io/stackstorm/packagingenv:deb
  volumes:
    - /tmp/st2-packages:/root/build

buildenvrpm:
  image: quay.io/stackstorm/packagingenv:rpm
  volumes:
    - /tmp/st2-packages:/root/build

# Test innstances
itrusty:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  volumes_from:
    - buildenvdeb

icentos7:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

ubuntu:
  image: quay.io/dennybaa/droneruby
  working_dir: /root/workdir
  entrypoint: ["/bin/bash", "/root/workdir/.drone/build.sh"]
  environment:
    # Full list of st2 packages configures the default build
    - COMPOSE=1
    - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor
    - ST2_GITURL=https://github.com/dennybaa/st2.git
    - ST2_GITREV=setuptools_packaging_improvements
    # - BUILDLIST=
    - BUILDHOST=buildenvdeb
    - TESTHOSTS=itrusty
    - DEBUG=1
  links:
    - buildenvdeb
    - rabbitmq
    - mongodb
    - itrusty
  volumes:
    - .:/root/workdir
    - /tmp/st2-packages:/root/packages

centos:
  image: quay.io/dennybaa/droneruby
  working_dir: /root/workdir
  entrypoint: ["/bin/bash", "/root/workdir/.drone/build.sh"]
  environment:
    # Full list of st2 packages configures the default build
    - COMPOSE=1
    - ST2_PACKAGES=st2common st2actions st2api st2auth st2client st2reactor
    - ST2_GITURL=https://github.com/dennybaa/st2.git
    - ST2_GITREV=setuptools_packaging_improvements
    # - BUILDLIST=
    - BUILDHOST=buildenvrpm
    # - TESTHOSTS=trusty
    - DEBUG=1
  links:
    - buildenvrpm
    # - rabbitmq
    # - mongodb
    # - icentos7
  volumes:
    - .:/root/workdir
    # - /sys/fs/cgroup:/sys/fs/cgroup
    - /tmp/st2-packages:/root/packages
