wheezy:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose.yml
    service: suite-circle
  environment:
    - BUILDNODE=wheezybuild
    - TESTNODE=wheezytest
  links:
    - wheezybuild
    - wheezytest

jessie:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose.yml
    service: suite-circle
  environment:
    - BUILDNODE=jessiebuild
    - TESTNODE=jessietest
  links:
    - jessiebuild
    - jessietest

trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose.yml
    service: suite-circle
  environment:
    - BUILDNODE=trustybuild
    - TESTNODE=trustytest
  links:
    - trustybuild
    - trustytest

centos7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose.yml
    service: suite-circle
  environment:
    - BUILDNODE=centos7build
    - TESTNODE=centos7test
  links:
    - centos7build
    - centos7test

centos6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose.yml
    service: suite-circle
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
    - TESTNODE=centos6test
  links:
    - centos6build
    - centos6test
