# Suite runners prefrom build -> install -> test
# see also compose-suite.yml
#
#   - Build is not run if BUILDHOST is an empty string.
#   - Integration tests are not run if BUILDLIST differs from ST2_PACKAGES (all available packages).
#   - Integration tests can be DISABLED if you set TESTHOSTS to an empty string.
#

# wheezy (previous), light one, number one to be containerized.
debian:
  image: quay.io/dennybaa/droneruby
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDHOST=bwheezy
    - TESTHOSTS=iwheezy
  links:
    - bwheezy
    - iwheezy
    - rabbitmq
    - mongodb

# 14.04
ubuntu:
  image: quay.io/dennybaa/droneruby
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDHOST=btrusty
    - TESTHOSTS=itrusty
  links:
    - btrusty
    - itrusty
    - rabbitmq
    - mongodb

centos7:
  image: quay.io/dennybaa/droneruby
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDHOST=bcentos7
    - TESTHOSTS=icentos7
  links:
    - bcentos7
    - icentos7
    - rabbitmq
    - mongodb

# -----------------------------------------------------------------------------

# External Services
#
rabbitmq:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "15672:15672"  # managment plugin port
    - "5672:5672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"

# Build Instances
#
bwheezy:
  image: quay.io/stackstorm/packagingenv:wheezy
  volumes:
    - /tmp/st2-packages:/root/build

btrusty:
  image: quay.io/stackstorm/packagingenv:trusty
  volumes:
    - /tmp/st2-packages:/root/build

bcentos7:
  image: quay.io/stackstorm/packagingenv:centos7
  volumes:
    - /tmp/st2-packages:/root/build

# Test Instances
#
itrusty:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  volumes:
    - /tmp/st2-packages:/root/build

iwheezy:
  image: quay.io/dennybaa/droneunit:wheezy
  command: /usr/sbin/sshd -D
  volumes:
    - /tmp/st2-packages:/root/build

icentos7:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /tmp/st2-packages:/root/build
