wheezy:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=wheezybuild
    - TESTNODE=wheezytest
  links:
    - wheezybuild
    - wheezytest

trusty:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=trustybuild
  links:
    - trustybuild

centos7:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - BUILDNODE=centos7build
  links:
    - centos7build

centos6:
  image: quay.io/stackstorm/packagingrunner
  extends:
    file: compose-suite.yml
    service: suite
  environment:
    - ST2_PYTHON=1
    - BUILDNODE=centos6build
  links:
    - centos6build

rabbitmq:
  image: rabbitmq:management
  hostname: rabbit
  ports:
    - "15672:15672"  # managment plugin port
    - "5672:5672"

mongodb:
  image: mongo
  ports:
    - "27017:27017"

postgres:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=mistral
    - POSTGRES_PASSWORD=StackStorm

# Package build nodes
wheezybuild:
  image: quay.io/stackstorm/packagingenv:wheezy
  extends:
    file: compose-suite.yml
    service: artifacts_volume

trustybuild:
  image: quay.io/stackstorm/packagingenv:trusty
  extends:
    file: compose-suite.yml
    service: artifacts_volume

centos6build:
  image: quay.io/stackstorm/packagingenv:centos6
  extends:
    file: compose-suite.yml
    service: artifacts_volume

centos7build:
  image: quay.io/stackstorm/packagingenv:centos7
  extends:
    file: compose-suite.yml
    service: artifacts_volume


# Package testing nodes
wheezytest:
  image: quay.io/dennybaa/droneunit:wheezy-sshd
  extends:
    file: compose-suite.yml
    service: artifacts_volume

trustytest:
  image: quay.io/dennybaa/droneunit:trusty-upstart
  extends:
    file: compose-suite.yml
    service: artifacts_volume

centos6test:
  image: quay.io/dennybaa/droneunit:centos6-sshd
  extends:
    file: compose-suite.yml
    service: artifacts_volume

centos7test:
  image: quay.io/dennybaa/droneunit:centos7-systemd
  extends:
    file: compose-suite.yml
    service: artifacts_volume
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
